#!/usr/bin/env python3
"""Glyphs for libqrt's text: Inter at 15 and 23 px, printable ASCII, 8-bit coverage.
usage: genfont.py assets/Inter-Regular.ttf out.c"""
import sys
from PIL import Image, ImageDraw, ImageFont

sizes = [15, 23]
bits, glyphs, lines = [], [], []
for px in sizes:
    font = ImageFont.truetype(sys.argv[1], px)
    asc, desc = font.getmetrics()
    lines.append(asc + desc)
    row = []
    for c in range(32, 127):
        ch = chr(c)
        adv = int(round(font.getlength(ch)))
        box = font.getbbox(ch)                      # relative to the origin at the top of the ascent
        w, h = max(0, box[2] - box[0]), max(0, box[3] - box[1])
        off = len(bits)
        if w and h:
            img = Image.new('L', (w, h), 0)
            ImageDraw.Draw(img).text((-box[0], -box[1]), ch, font=font, fill=255)
            bits.extend(img.tobytes())
        row.append((adv, box[0], box[1], w, h, off))
    glyphs.append(row)

out = ['/* Generated by sdk/libqrt/genfont.py from Inter (SIL Open Font License) - do not edit. */',
       'typedef struct { short adv, x, y, w, h; int off; } qrt_glyph;',
       'const int qrt_line_h[2] = { %d, %d };' % tuple(lines),
       'const qrt_glyph qrt_glyphs[2][95] = {']
for row in glyphs:
    out.append('  {' + ', '.join('{%d,%d,%d,%d,%d,%d}' % g for g in row) + '},')
out.append('};')
out.append('const unsigned char qrt_glyph_bits[%d] = {' % max(1, len(bits)))
for i in range(0, len(bits), 32):
    out.append('  ' + ','.join(str(b) for b in bits[i:i + 32]) + ',')
out.append('};')
open(sys.argv[2], 'w').write('\n'.join(out) + '\n')
