#!/usr/bin/env python3
# angle-stub.py INCLUDE_DIR - a C file defining every EGL and GLES (2, 3, extensions)
# entry point in ANGLE's headers as a function that does nothing and returns 0
# (EGL_NO_DISPLAY, EGL_FALSE, ...).  Used by ports/angle.sh.
import re, sys
inc = sys.argv[1]
headers = ["EGL/egl.h", "EGL/eglext.h", "EGL/eglext_angle.h", "GLES2/gl2.h", "GLES2/gl2ext.h",
           "GLES2/gl2ext_angle.h", "GLES3/gl3.h", "GLES3/gl31.h", "GLES3/gl32.h"]
proto = re.compile(r"^(?:EGLAPI|GL_APICALL)\s+(.+?)\s*(?:EGLAPIENTRY|GL_APIENTRY)\s+(\w+)\s*\((.*?)\);", re.S | re.M)
seen, out = set(), []
print("// generated by ports/angle-stub.py: no GPU")
print("#define EGL_EGL_PROTOTYPES 1\n#define GL_GLES_PROTOTYPES 1\n#define GL_GLEXT_PROTOTYPES 1\n#define EGL_EGLEXT_PROTOTYPES 1")
for h in headers:
    print(f"#include <{h}>")
    for ret, name, args in proto.findall(open(f"{inc}/{h}").read()):
        if name in seen: continue
        seen.add(name)
        ret = " ".join(ret.split())
        body = "" if ret == "void" else f"return ({ret})0;"
        out.append(f"{ret} {name}({' '.join(args.split())}) {{ {body} }}")
print("#pragma clang diagnostic ignored \"-Wunused-parameter\"")
print("\n".join(out))
