VERSION=8.21.0
fetch() { fetch_git https://github.com/curl/curl curl-${VERSION//./_}; }
build() { cmake_build . -DBUILD_CURL_EXE=OFF -DBUILD_LIBCURL_DOCS=OFF -DBUILD_MISC_DOCS=OFF -DENABLE_CURL_MANUAL=OFF -DCURL_USE_OPENSSL=ON -DUSE_NGHTTP2=ON -DCURL_BROTLI=ON -DCURL_ZSTD=ON -DCURL_USE_LIBPSL=ON -DUSE_LIBIDN2=OFF -DCURL_USE_LIBSSH2=OFF -DCURL_USE_GSSAPI=OFF -DENABLE_WEBSOCKETS=ON -DCURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt -DCURL_CA_PATH=none -DCURL_DISABLE_LDAP=ON -DENABLE_THREADED_RESOLVER=ON; }
