#!/bin/sh
# sdk/build-cxx.sh [SDK] - C++ for native QRT programs: LLVM 20's compiler-rt (builtins,
# crtbegin/crtend), libunwind, libc++abi and libc++, built static for QRT's musl and
# installed into the SDK's sysroot; then qrt-c++, and a CMake toolchain file
# (SDK/qrt.cmake) for building libraries and programs for QRT.
#
# Needs: the C SDK (sdk/build.sh), clang-20/lld-20 (Ubuntu 24.04: apt install clang-20
# lld-20 llvm-20), CMake >= 3.20, ninja, git.  LLVM's sources (only the runtimes, about
# 250 MB) are fetched once into SDK/src/llvm.
set -eu
here=$(cd "$(dirname "$0")" && pwd)
root=$(cd "$here/.." && pwd)
sdk=${1:-$root/build/sdk}
sdk=$(cd "$sdk" && pwd)
sys="$sdk/sysroot"
LLVM_TAG=llvmorg-20.1.2
src="$sdk/src/llvm"

if [ ! -d "$src/runtimes" ]; then
    git clone -q --depth 1 --branch "$LLVM_TAG" --filter=blob:none --sparse https://github.com/llvm/llvm-project "$src"
    (cd "$src" && git sparse-checkout set runtimes libcxx libcxxabi libunwind compiler-rt libc cmake llvm/cmake llvm/utils/llvm-lit third-party)
fi

# the toolchain file: the same one programs and libraries are built with afterwards
cat > "$sdk/qrt.cmake" <<EOF
# CMake toolchain file for native QRT programs (generated by sdk/build-cxx.sh)
set(CMAKE_SYSTEM_NAME Linux)          # Linux-like: QRT keeps Linux's interfaces under its own ABI
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(QRT ON)
set(CMAKE_SYSROOT "$sys")
set(CMAKE_C_COMPILER clang-20)
set(CMAKE_CXX_COMPILER clang++-20)
set(CMAKE_ASM_COMPILER clang-20)
set(CMAKE_C_COMPILER_TARGET x86_64-linux-musl)
set(CMAKE_CXX_COMPILER_TARGET x86_64-linux-musl)
set(CMAKE_ASM_COMPILER_TARGET x86_64-linux-musl)
set(CMAKE_AR /usr/bin/llvm-ar-20)
set(CMAKE_RANLIB /usr/bin/llvm-ranlib-20)
set(CMAKE_C_FLAGS_INIT "-D__QRT__")
set(CMAKE_CXX_FLAGS_INIT "-D__QRT__ -stdlib=libc++")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-static -fuse-ld=lld -rtlib=compiler-rt -unwindlib=libunwind -stdlib=libc++")
set(CMAKE_FIND_ROOT_PATH "$sys")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(BUILD_SHARED_LIBS OFF CACHE BOOL "static only")
set(ENV{PKG_CONFIG_LIBDIR} "$sys/usr/lib/pkgconfig:$sys/usr/share/pkgconfig")
set(ENV{PKG_CONFIG_SYSROOT_DIR} "$sys")
EOF

b="$sdk/rt"
rm -rf "$b"
cmake -G Ninja -S "$src/runtimes" -B "$b" -DCMAKE_TOOLCHAIN_FILE="$sdk/qrt.cmake" \
    -DCMAKE_TRY_COMPILE_TARGET_TYPE=STATIC_LIBRARY -DCMAKE_CXX_FLAGS_INIT= -DCMAKE_EXE_LINKER_FLAGS_INIT= \
    -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$sys/usr" \
    -DLLVM_ENABLE_RUNTIMES="compiler-rt;libunwind;libcxxabi;libcxx" \
    -DCOMPILER_RT_BUILD_BUILTINS=ON -DCOMPILER_RT_BUILD_CRT=ON -DCOMPILER_RT_BUILD_SANITIZERS=OFF \
    -DCOMPILER_RT_BUILD_XRAY=OFF -DCOMPILER_RT_BUILD_LIBFUZZER=OFF -DCOMPILER_RT_BUILD_PROFILE=OFF \
    -DCOMPILER_RT_BUILD_MEMPROF=OFF -DCOMPILER_RT_BUILD_ORC=OFF -DCOMPILER_RT_BUILD_CTX_PROFILE=OFF \
    -DCOMPILER_RT_DEFAULT_TARGET_ONLY=ON -DCOMPILER_RT_INCLUDE_TESTS=OFF \
    -DLIBUNWIND_ENABLE_SHARED=OFF -DLIBUNWIND_USE_COMPILER_RT=ON -DLIBUNWIND_INCLUDE_TESTS=OFF \
    -DLIBCXXABI_ENABLE_SHARED=OFF -DLIBCXXABI_USE_LLVM_UNWINDER=ON -DLIBCXXABI_USE_COMPILER_RT=ON \
    -DLIBCXXABI_ENABLE_STATIC_UNWINDER=ON -DLIBCXXABI_INCLUDE_TESTS=OFF \
    -DLIBCXX_ENABLE_SHARED=OFF -DLIBCXX_HAS_MUSL_LIBC=ON -DLIBCXX_USE_COMPILER_RT=ON -DLIBCXX_CXX_ABI=libcxxabi \
    -DLIBCXX_ENABLE_STATIC_ABI_LIBRARY=ON -DLIBCXX_INCLUDE_BENCHMARKS=OFF -DLIBCXX_INCLUDE_TESTS=OFF >/dev/null
ninja -C "$b" >/dev/null
ninja -C "$b" install >/dev/null

# compiler-rt installs under lib/linux/ with an arch suffix; clang-20 looks for a target's
# runtime in its own resource directory (lib/x86_64-unknown-linux-musl/libclang_rt.builtins.a),
# so it is copied there - the one change outside the SDK (needs write access to /usr/lib/llvm-20)
rtdir="$(clang-20 -print-resource-dir)/lib/x86_64-unknown-linux-musl"
mkdir -p "$rtdir"
for f in "$sys"/usr/lib/linux/libclang_rt.builtins-x86_64.a "$sys"/usr/lib/linux/clang_rt.crtbegin-x86_64.o "$sys"/usr/lib/linux/clang_rt.crtend-x86_64.o; do
    [ -f "$f" ] || continue
    n=$(basename "$f" | sed 's/-x86_64//')
    cp "$f" "$rtdir/$n"
done

# drivers: C and C++ with compiler-rt, libunwind and libc++, everything static
cat > "$sdk/bin/qrt-c++" <<EOF
#!/bin/sh
# qrt-c++: clang++ for native QRT programs (C++23, libc++, static)
exec clang++-20 --target=x86_64-linux-musl --sysroot="$sys" -D__QRT__ -static -fuse-ld=lld -rtlib=compiler-rt -unwindlib=libunwind -stdlib=libc++ "\$@"
EOF
cat > "$sdk/bin/qrt-cc20" <<EOF
#!/bin/sh
# qrt-cc20: clang-20 for native QRT programs, with compiler-rt instead of libgcc
exec clang-20 --target=x86_64-linux-musl --sysroot="$sys" -D__QRT__ -static -fuse-ld=lld -rtlib=compiler-rt -unwindlib=libunwind "\$@"
EOF
chmod +x "$sdk/bin/qrt-c++" "$sdk/bin/qrt-cc20"
echo "QRT C++ SDK: $sdk/bin/qrt-c++, toolchain file $sdk/qrt.cmake"
