#!/usr/bin/env python3
"""Generate src/arch/x64/isr.S: 256 interrupt entry stubs plus the common
entry path.  The output is committed; rerun after changing the layout:

    tools/gen_isr.py > src/arch/x64/isr.S
"""
ERROR_CODE_VECTORS = {8, 10, 11, 12, 13, 14, 17, 21, 29, 30}

COMMON = """
isr_common:
    testb $3, 24(%rsp)          /* interrupted CS: from user mode? */
    jz 1f
    swapgs
1:  pushq %rax
    pushq %rbx
    pushq %rcx
    pushq %rdx
    pushq %rsi
    pushq %rdi
    pushq %rbp
    pushq %r8
    pushq %r9
    pushq %r10
    pushq %r11
    pushq %r12
    pushq %r13
    pushq %r14
    pushq %r15
    movq %rsp, %r12             /* frame_t *, callee-saved across the call */
    subq $528, %rsp
    andq $-16, %rsp
    fxsave64 (%rsp)
    movq %r12, %rcx
    subq $32, %rsp              /* shadow space */
    cld
    call isr_dispatch
    addq $32, %rsp
    fxrstor64 (%rsp)
    movq %r12, %rsp
    popq %r15
    popq %r14
    popq %r13
    popq %r12
    popq %r11
    popq %r10
    popq %r9
    popq %r8
    popq %rbp
    popq %rdi
    popq %rsi
    popq %rdx
    popq %rcx
    popq %rbx
    popq %rax
    testb $3, 24(%rsp)
    jz 2f
    swapgs
2:  addq $16, %rsp
    iretq

    .data
    .p2align 3
    .globl isr_table
isr_table:"""


def main():
    out = ["/* isr.S - interrupt entry stubs, generated by tools/gen_isr.py.",
           " * Every vector pushes (error code, vector) and joins isr_common, which saves",
           " * the general registers and the FPU/SSE state, switches GS for user-mode",
           " * entries and calls isr_dispatch(frame) with the Microsoft x64 ABI. */",
           "    .text"]
    for n in range(256):
        out.append(f"isr{n}:")
        if n not in ERROR_CODE_VECTORS:
            out.append("    pushq $0")
        out.append(f"    pushq ${n}")
        out.append("    jmp isr_common")
    out.append(COMMON)
    out += [f"    .quad isr{n}" for n in range(256)]
    print("\n".join(out))


if __name__ == "__main__":
    main()
