#!/usr/bin/env python3
"""sdk/syscalls.txt -> src/arch/x64/native_sys.h: QRT native call number -> the Linux
call with the same semantics (0xffff: none), and the numbers of the QRT-only calls."""
import sys
rows = [l.split() for l in open(sys.argv[1]) if l.strip() and not l.startswith('#')]
top = max(int(r[0]) for r in rows if r[2] != '-')
table = ['0xffff'] * (top + 1)
qrt = []
for n, name, lin in rows:
    if lin == '-': qrt.append((int(n), name))
    else: table[int(n)] = lin
out = ['/* Generated by tools/gen_native_sys.py from sdk/syscalls.txt - do not edit. */', '#pragma once', '',
       '#define QRT_NR_LINUX_TOP %d' % top,
       'static const u16 qrt_to_linux[%d] = {' % (top + 1)]
for i in range(0, len(table), 12):
    out.append('    ' + ', '.join(table[i:i + 12]) + ',')
out.append('};')
for n, name in qrt:
    out.append('#define QRT_SYS_%s %d' % (name[4:].upper(), n))
open(sys.argv[2], 'w').write('\n'.join(out) + '\n')
