#!/usr/bin/env python3
"""Rasterise Inter (UI) and DejaVu Sans Mono (Terminal) into anti-aliased
glyph atlases for the QRT shell.

Output is a C file with 8-bit coverage bitmaps; the kernel has no font
engine, so all hinting/AA happens here at build time.

usage: tools/mkfont.py assets/ src/ui/fontdata.c
"""
import sys
from PIL import Image, ImageDraw, ImageFont

ASCII = [chr(c) for c in range(32, 127)]
EXTRA = ["•", "×", "°", "·", "…", "←", "→", "↑", "↓"]
DIGITS = list(" 0123456789:")

# (id, file, sizes, charset-for-size)
FACES = [
    ("regular", "Inter-Regular.ttf", [13, 15, 17, 20, 23, 27, 31, 36], lambda s: ASCII + EXTRA),
    ("semibold", "Inter-SemiBold.ttf", [13, 15, 17, 20, 23, 27, 31, 36, 42, 48, 56], lambda s: ASCII + EXTRA),
    ("light", "InterDisplay-Light.ttf", [40, 56, 72, 96, 120, 144, 176],
     lambda s: ASCII + EXTRA if s <= 72 else DIGITS),
    ("mono", "DejaVuSansMono.ttf", [12, 13, 15, 17, 20, 23], lambda s: ASCII + EXTRA),
]


def render_face(path, size, chars):
    font = ImageFont.truetype(path, size)
    ascent, descent = font.getmetrics()
    glyphs, bits = [], bytearray()
    for ch in chars:
        adv = font.getlength(ch)
        x0, y0, x1, y1 = font.getbbox(ch)  # relative to (0,0) at ascender line
        w, h = max(0, x1 - x0), max(0, y1 - y0)
        off = len(bits)
        if w and h:
            img = Image.new("L", (w, h), 0)
            ImageDraw.Draw(img).text((-x0, -y0), ch, font=font, fill=255)
            bits += img.tobytes()
        glyphs.append((ord(ch), w, h, x0, y0, round(adv * 64), off))
    return ascent, ascent + descent, glyphs, bits


def main():
    assets, out = sys.argv[1], sys.argv[2]
    lines = ['/* generated by tools/mkfont.py from Inter (SIL OFL 1.1) - do not edit */',
             '#include "font.h"', '']
    table = {}
    for fid, fname, sizes, charset in FACES:
        table[fid] = []
        for size in sizes:
            ascent, line_h, glyphs, bits = render_face(f"{assets}/{fname}", size, charset(size))
            name = f"{fid}_{size}"
            lines.append(f"static const glyph_t g_{name}[] = {{")
            for cp, w, h, bx, by, adv, off in glyphs:
                lines.append(f"  {{{cp},{w},{h},{bx},{by},{adv},{off}}},")
            lines.append("};")
            lines.append(f"static const u8 b_{name}[{max(1, len(bits))}] = {{")
            for i in range(0, len(bits), 32):
                lines.append("  " + ",".join(str(b) for b in bits[i:i + 32]) + ",")
            lines.append("};")
            table[fid].append(f"  {{{size},{ascent},{line_h},{len(glyphs)},g_{name},b_{name}}},")
    for fid, entries in table.items():
        lines.append(f"const font_t font_{fid}[] = {{")
        lines += entries
        lines.append("  {0},")
        lines.append("};")
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
