#!/usr/bin/env python3
"""symtab.py MAP OUT.c - the kernel's function names for its crash screen.

Reads lld-link's map of a first link (text symbols: section 0001) and writes a C file with
their offsets from the image base and their names; the final link adds it.  It only adds
read-only data after the code, so the code's addresses in the map stay the same."""
import re, sys

base = 0x140000000
syms = []
for line in open(sys.argv[1]):
    m = re.match(r'\s*0001:[0-9a-f]+\s+(\S+)\s+([0-9a-f]{16})\s', line)
    if m:
        name = m.group(1)
        if name.startswith(('.', '$', '__imp_')) or 'reltable' in name:
            continue
        syms.append((int(m.group(2), 16) - base, name[:40]))
syms = sorted(set(syms))
with open(sys.argv[2], 'w') as o:
    o.write("/* generated by tools/symtab.py from the first link's map: the kernel's functions */\n")
    o.write("const unsigned qrt_nsyms = %d;\n" % len(syms))
    o.write("const unsigned qrt_sym_off[] = {%s};\n" % ",".join("0x%x" % a for a, _ in syms) if syms else "const unsigned qrt_sym_off[1] = {0};\n")
    names, offs, pos = [], [], 0
    for _, n in syms:
        offs.append(pos)
        names.append(n)
        pos += len(n) + 1
    o.write("const unsigned qrt_sym_name[] = {%s};\n" % ",".join(str(x) for x in offs) if syms else "const unsigned qrt_sym_name[1] = {0};\n")
    o.write("const char qrt_sym_str[] = \"%s\";\n" % "\\0".join(names))
